server:
  port: 81
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: 1414
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 455750352833-v4cop0rqraeavnga47taqdhuepmsnlda.apps.googleusercontent.com
            client-secret: ZzbMmC2M5BG7b0kn50yIKcS1
            scope:
            - email
            - profile
          
